- .gitignore
- Cargo.toml
- README.md
- src/abi/generation.rs
- src/abi/mod.rs
- src/cargo/manifest.rs
- src/cargo/metadata.rs
- src/cargo/mod.rs
- src/main.rs
- src/util.rs
- templates/_Cargo.toml
This iteration of cargo-near follows the new approach with dynamic linking to a shared library that I presented before.
~A couple of places presume ELF (filtering by `.so` suffix, stripping `lib` prefix from the shared library), but I think with minimal tweaks the same will work for MachO and PE.~ UPD: made some tweaks, works on Linux & macOS (M1, but should not matter I think). I don't have easy access to a Windows machine so that would have to be done a bit later.
`prettyprint` and `syn` dependencies could be removed, but I thought generating readable code would be nice (especially since I am logging it for visibility).
> feat: MVP of ABI generation

- cargo-near/Cargo.toml
- cargo-near/src/abi/generation.rs
- cargo-near/src/abi/mod.rs
- cargo-near/src/util.rs
- cargo-near/templates/_Cargo.toml
- integration-tests/Cargo.toml
Fixes #8 
This PR introduces three compilation time improvements:
1. Removes `nearcore` crate dependencies from the generated abigen crates (reduces compilation time from 22.5s to 10.5s on `abi` example in NEAR SDK).
2. Makes the generated abigen crates use `dev` profile with disabled optimizations and disabled LTO (reduces compilation town from 10.5s further to 9.5s)
3. Makes the original (user-written) crate use `dev` profile with disabled optimizations and disabled LTO through cargo envvars (reduces dylib compilation time from 25s to 21.5s).
> feat: optimize ABI generation time

- .github/workflows/test.yml
We were already tight on CI storage, probably best for these to avoid using the cache for now
> chore: remove cache from CI

- .github/workflows/test.yml
- cargo-near/Cargo.toml
Context: #24. Supersedes #26.
Ensures `cargo-near` remains compilable with the MSRV.
> cargo check msrv

- cargo-near/src/abi/mod.rs
- cargo-near/src/build.rs
Based off #31
- `cargo near build`
- Not sure what `cargo near abi` would look like, went with the back ticked version in this PR.
> abi: paint build reports

- cargo-near/src/abi.rs
- integration-tests/src/lib.rs
Tracking issue: https://github.com/near/cargo-near/issues/41
Supersedes #24.
Current integration tests generate isolated projects with distinct target folders despite compiling ~99% of the same artifacts.
Causing current CI runs to run upwards of an hour.
With this patch, CI completes in under 10 minutes.
---
Based on #35, because in my tests, leaving the codegen in caused inconsistent results, ~didn't bother investigating why. https://github.com/near/cargo-near/runs/8050886022?check_suite_focus=true~
I eventually looked into it. See #40 for an alternative that merges straight into the main branch.
> use shared target folder for faster CI

- cargo-near/Cargo.toml
- cargo-near/src/abi.rs
- cargo-near/src/build.rs
- cargo-near/src/lib.rs
- integration-tests/src/lib.rs
- integration-tests/templates/_Cargo.toml
- integration-tests/templates/_Cargo_no_abi_feature.toml
- integration-tests/templates/sdk-dependency/_Cargo_explicit.toml
- integration-tests/templates/sdk-dependency/_Cargo_multiple_features.toml
- integration-tests/templates/sdk-dependency/_Cargo_no_default_features.toml
- integration-tests/templates/sdk-dependency/_Cargo_patch.toml
- integration-tests/templates/sdk-dependency/_Cargo_platform_specific.toml
- integration-tests/templates/sdk-dependency/_Cargo_renamed.toml
- integration-tests/tests/cargo/mod.rs
Still WIP, opening for visibility.
Table below shows some tests that I have done. Cell values are the size of the abi file after serialization+compression in bytes.
<table>
<tr>
<td> ser+comp / contract
<td> abi
<td> ft
<td> nft
<tr>
<td> JSON (min)
<td> 1694
<td> 4834
<td> 7148
<tr>
<td> JSON (min)+snap
<td> 672
<td> 1265
<td> 1590
<tr>
<td> JSON (min)+zstd
<td> 498
<td> 914
<td> 1113
<tr>
<td> CBOR
<td> 1379
<td> 3991
<td> 5842
<tr>
<td> CBOR+snap
<td> 602
<td> 1239
<td> 1580
<tr>
<td> CBOR+zstd
<td> 480
<td> 909
<td> 1132
</table>
> feat: add binary serialization formats and compression when embedding

- integration-tests/templates/_Cargo.toml
- integration-tests/templates/_Cargo_no_abi_feature.toml
- integration-tests/templates/sdk-dependency/_Cargo_explicit.toml
- integration-tests/templates/sdk-dependency/_Cargo_local_path_with_version.toml
- integration-tests/templates/sdk-dependency/_Cargo_multiple_features.toml
- integration-tests/templates/sdk-dependency/_Cargo_no_default_features.toml
- integration-tests/templates/sdk-dependency/_Cargo_patch.toml
- integration-tests/templates/sdk-dependency/_Cargo_platform_specific.toml
- integration-tests/templates/sdk-dependency/_Cargo_renamed.toml
- integration-tests/tests/cargo/mod.rs
This should effectively match the state it was in before ABI PRs were merged in. But with the version update.
> update near-sdk in integration tests to pre-released version

- cargo-near/src/util/mod.rs
Context: https://github.com/near/cargo-near/pull/63#issuecomment-1278800638
Skips the message parsing redundancy and stdout buffer.
> report cargo stdout errors immediately

- cargo-near/src/abi.rs
- cargo-near/src/build.rs
- cargo-near/src/util/mod.rs
Fixes #67
Hides warnings at the ABI generation stage only when building contracts
| Before | After |
| :-: | :-: |
| <img width="656" alt="CleanShot 2022-10-15 at 11 57 47@2x" src="https://user-images.githubusercontent.com/16881812/195976122-1141a1a4-5202-46fa-a6c3-f8eda064c3b0.png"> | <img width="664" alt="CleanShot 2022-10-15 at 11 55 35@2x" src="https://user-images.githubusercontent.com/16881812/195976036-b73c53f9-e7d2-430b-9fc9-730f6f4b59e2.png"> |
> Deduplicate warnings

- cargo-near/src/main.rs
Context: https://github.com/near/cargo-near/pull/69#pullrequestreview-1143536734
- Step Contextualized
---
- `cargo` runs
---
- Generic
> replace error text with symbol

- .github/workflows/test.yml
GitHub's matrix behavior is a little weird. By default, when one path causes an execution to fail, GitHub auto-cancels all other executions from the same matrix.
Example: https://github.com/near/cargo-near/actions/runs/3271855547/attempts/2
Ideally, we should test each one independently, and get all the possible errors/successes all at once, instead of incrementally.
> CI: run matrix paths independently

- Cargo.lock
- cargo-near/Cargo.toml
- cargo-near/src/abi.rs
- cargo-near/src/build.rs
- cargo-near/src/cargo/manifest.rs
- cargo-near/src/cargo/metadata.rs
- cargo-near/src/lib.rs
- cargo-near/src/util/mod.rs
- integration-tests/Cargo.toml
- integration-tests/src/lib.rs
Neither `cargo` nor `rustc` support non-utf8 names/paths.
| `rustc` | `cargo` |
| :-: | :-: |
| <img width="359" alt="CleanShot 2022-10-19 at 17 10 42@2x" src="https://user-images.githubusercontent.com/16881812/196700352-6d1a22b0-277f-482d-bcb2-f7c9c8855eba.png"> | <img width="422" alt="CleanShot 2022-10-19 at 17 07 30@2x" src="https://user-images.githubusercontent.com/16881812/196699637-ce90215f-c7fe-4bc9-a8b4-8bd8e03a63ba.png"> |
And while `cargo-near` currently accepts non-utf8 inputs, it panics at a `fs` operation.
This patch pre-emptively returns a helpful error.
> only accept UTF-8 inputs

- cargo-near/src/cargo/metadata.rs
This should've been a part of #75.
`target/near` should be created at this stage if it doesn't already exist.
> create the target/near directory, if it doesn't already exist

- cargo-near/src/main.rs
Keeping in line with the rest of the styling.
| Before | After |
| :-: | :-: |
| <img width="494" alt="CleanShot 2022-10-20 at 05 32 40@2x" src="https://user-images.githubusercontent.com/16881812/196835149-90ce9e6e-9ad9-4fc2-b490-ad0af49dc34e.png"> | <img width="494" alt="CleanShot 2022-10-20 at 05 31 07@2x" src="https://user-images.githubusercontent.com/16881812/196835084-61c251ff-5b07-499b-a87e-c0a48b11343c.png"> |
> indent errors

- Cargo.lock
- cargo-near/Cargo.toml
- cargo-near/src/abi.rs
- cargo-near/src/build.rs
- integration-tests/Cargo.toml
- integration-tests/templates/_Cargo.toml
- integration-tests/templates/sdk-dependency/_Cargo_explicit.toml
- integration-tests/templates/sdk-dependency/_Cargo_multiple_features.toml
- integration-tests/templates/sdk-dependency/_Cargo_no_default_features.toml
- integration-tests/templates/sdk-dependency/_Cargo_patch.toml
- integration-tests/templates/sdk-dependency/_Cargo_platform_specific.toml
- integration-tests/templates/sdk-dependency/_Cargo_renamed.toml
- integration-tests/tests/abi/borsh_schema.rs
- integration-tests/tests/abi/callbacks.rs
- integration-tests/tests/abi/e2e.rs
- integration-tests/tests/abi/json_schema.rs
- integration-tests/tests/build/embed.rs
- integration-tests/tests/build/mod.rs
- integration-tests/tests/build/opts.rs
- integration-tests/tests/cargo/mod.rs
- integration-tests/tests/lib.rs
- integration-tests/tests/util.rs
Fixes #19 
Depends on https://github.com/near/near-sdk-rs/pull/927
> feat: populate metadata with build information

- cargo-near/src/cargo/metadata.rs
So this exists. Did we use the old pattern to provide specific error messages? If so, I'm not sure how helpful they are to a user.
> simplify root extraction

- CHANGELOG.md
- Cargo.lock
- cargo-near/Cargo.toml
> Following https://github.com/near/cargo-near/pull/90, PRs like these, once merged into master, automatically trigger a release.
Scheduled release: 10-11-2022
Changes:
- The minimum supported version of the SDK for this release is `4.1.0`.
- Upgraded the `near-abi` version to `0.3.0`. <https://github.com/near/cargo-near/pull/83> 
- The exported and embedded ABI now includes build information. <https://github.com/near/cargo-near/pull/55> 
- When building a contract, the exported ABI now also includes the code hash of the built contract. <https://github.com/near/cargo-near/pull/55> 
- Fixed a situation where `cargo-near` could potentially run into segfaults when working with incompatible versions of the SDK. <https://github.com/near/cargo-near/pull/74> 
- `cargo-near` now only accepts …
> chore: release 0.3.0

- cargo-near/src/build.rs
- cargo-near/src/lib.rs
The build module was made public  to access run method which  helps in resolving [issue  ](https://github.com/near/workspaces-rs/issues/230 issue by replacing ) in [workspace-rs](https://github.com/near/workspaces-rs)
by replacing existing build logic with cargo-nears build logic.
> Make build , abi and util modules public 

- Cargo.lock
- cargo-near/CHANGELOG.md
- cargo-near/Cargo.toml
* `cargo-near`: 0.3.1 -> 0.4.0 (⚠️ API breaking changes)
```
--- failure enum_missing: pub enum removed or renamed ---
Description:
A publicly-visible enum cannot be imported by its prior path. A `pub use` may have been removed, or the enum itself may have been renamed or removed entirely.
ref: https://doc.rust-lang.org/cargo/reference/semver.html#item-remove
impl: https://github.com/obi1kenobi/cargo-semver-checks/tree/v0.23.0/src/lints/enum_missing.ron
Failed in:
enum cargo_near::NearCommand, previously in file /tmp/.tmpO8FnGy/cargo-near/src/lib.rs:26
enum cargo_near::ColorPreference, previously in file /tmp/.tmpO8FnGy/cargo-near/src/lib.rs:88
--- failure function_missing: pub fn removed or renamed ---
Description:
A publicly-visible function cannot be imported by its prior path. A `pub …
```
> chore: release v0.4.0

- Cargo.lock
- cargo-near/Cargo.toml
- cargo-near/src/util/mod.rs
Closes #4 
On Windows, `Path::canonicalize()` returns a path with the UNC prefix not supported by `cmd.exe` and breaks the compilation of all crates that have `include!` macros in it. The problem is well known, and no proper solution at the current moment https://github.com/rust-lang/rust/issues/42869 
For now, I just cut this UNC prefix, but if users complain about that, we can come out with a more sophisticated solution like https://lib.rs/crates/dunce
> fix: use `dunce` crate to remove UNC prefix

- Cargo.lock
- cargo-near/Cargo.toml
- cargo-near/src/commands/abi_command/mod.rs
- cargo-near/src/commands/build_command/mod.rs
- cargo-near/src/commands/create_dev_account/mod.rs
- cargo-near/src/commands/create_dev_account/use_random_account_id.rs
- cargo-near/src/commands/deploy/mod.rs
- cargo-near/src/commands/mod.rs
- cargo-near/src/lib.rs
- cargo-near/src/types/utf8_path_buf.rs
- integration-tests/src/lib.rs
> feat: New command - create-dev-account

- Cargo.lock
- cargo-near/CHANGELOG.md
- cargo-near/Cargo.toml
- cargo-near/src/commands/mod.rs
* `cargo-near`: 0.4.0 -> 0.5.0 (⚠️ API breaking changes)
```
--- failure enum_variant_added: enum variant added on exhaustive enum ---
Description:
A publicly-visible enum without #[non_exhaustive] has a new variant.
ref: https://doc.rust-lang.org/cargo/reference/semver.html#enum-variant-new
impl: https://github.com/obi1kenobi/cargo-semver-checks/tree/v0.24.0/src/lints/enum_variant_added.ron
Failed in:
variant NearCommandDiscriminants:CreateDevAccount in /tmp/.tmptlX4be/cargo-near/cargo-near/src/commands/mod.rs:31
variant NearCommandDiscriminants:Deploy in /tmp/.tmptlX4be/cargo-near/cargo-near/src/commands/mod.rs:34
variant NearCommandDiscriminants:CreateDevAccount in /tmp/.tmptlX4be/cargo-near/cargo-near/src/commands/mod.rs:31
variant NearCommandDiscriminants:Deploy in …
```
> chore: release v0.4.1

- Cargo.lock
- cargo-near/CHANGELOG.md
- cargo-near/Cargo.toml
- cargo-near/src/commands/new/mod.rs
- cargo-near/src/main.rs
* `cargo-near`: 0.4.1 -> 0.5.0 (⚠️ API breaking changes)
```
--- failure enum_variant_added: enum variant added on exhaustive enum ---
Description:
A publicly-visible enum without #[non_exhaustive] has a new variant.
ref: https://doc.rust-lang.org/cargo/reference/semver.html#enum-variant-new
impl: https://github.com/obi1kenobi/cargo-semver-checks/tree/v0.24.2/src/lints/enum_variant_added.ron
Failed in:
variant CliNearCommand:New in /tmp/.tmpgmFX3o/cargo-near/cargo-near/src/commands/mod.rs:9
variant NearCommandDiscriminants:New in /tmp/.tmpgmFX3o/cargo-near/cargo-near/src/commands/mod.rs:20
variant NearCommandDiscriminants:New in /tmp/.tmpgmFX3o/cargo-near/cargo-near/src/commands/mod.rs:20
```
<blockquote>
- New command to initialize a …
> chore: release v0.5.0

- Cargo.lock
- cargo-near/CHANGELOG.md
- cargo-near/Cargo.toml
* `cargo-near`: 0.5.0 -> 0.5.1 (✓ API compatible changes)
<blockquote>
- Upgraded NEAR crates to 0.20.0 release ([#125](https://github.com/near/cargo-near/pull/125))
- Updated binary releases pipeline to use cargo-dist v0.7.2 (previously v0.3.0)  ([#122](https://github.com/near/cargo-near/pull/122))
</blockquote>
</p></details>
---
> chore: release v0.5.1

- CHANGELOG.md
- Cargo.lock
- cargo-near/Cargo.toml
* `cargo-near`: 0.6.0 -> 0.6.1 (✓ API compatible changes)
<blockquote>
- Updated near-sdk-rs to version 5.0.0 for the new projects ([#132](https://github.com/near/cargo-near/pull/132))
</blockquote>
</p></details>
---
> chore: release v0.6.1

- Cargo.lock
- cargo-near/Cargo.toml
- cargo-near/src/commands/build_command/mod.rs
Passing uid, gid to container to preserve the privileges the same as for host system, while building to mounted volume from host.
- [append timestamp and pid to container name to make it unique](https://github.com/near/cargo-near/commit/fdc5ee6ebb97bd2fa7c80ebd71ec28b6b00b6524)
- [use image with non-root user builder](https://github.com/near/cargo-near/commit/f3c3b11eba7286bfefd9e956fe81a16611ea0efd)
- [implement cross-platform uid,gid support with platform-specific dependencies](https://github.com/near/cargo-near/pull/140/commits/40f98ba62fe59ad42099441e32a0839655d2ff74)
> Source scan integration pass uid and gid to container

- .github/workflows/test.yml
- cargo-near/src/commands/build_command/build.rs
- cargo-near/src/commands/build_command/docker.rs
- cargo-near/src/commands/build_command/docker/cloned_repo.rs
- cargo-near/src/commands/build_command/docker/git_checks.rs
- cargo-near/src/commands/build_command/docker/metadata.rs
- cargo-near/src/commands/build_command/mod.rs
- cargo-near/src/commands/deploy/mod.rs
- cargo-near/src/commands/mod.rs
- cargo-near/src/main.rs
- cargo-near/src/types/metadata.rs
- cargo-near/src/util/mod.rs
- cargo-near/src/util/print.rs
- integration-tests/src/lib.rs
Following output was generated by using the branch of current pr with [build local `cargo-near` Dockerfile](https://github.com/dj8yfo/cargo-near-image/tree/0.x.x-builer-local-cargo-near) => [image](https://hub.docker.com/r/dj8yfo/sourcescan/tags) on this [repo](https://github.com/dj8yfo/sample_no_workspace/tree/set_metadata)
> feat(source-scan): logging, refactor, image with same `cargo-near` embedded, remove `--no-docker` flag

- CHANGELOG.md
- Cargo.lock
- cargo-near/Cargo.toml
* `cargo-near`: 0.6.1 -> 0.6.2 (✓ API compatible changes)
<blockquote>
- Updated new project template with near-sdk-rs 5.1.0 ([#143](https://github.com/near/cargo-near/pull/143))
- Support nixOS - decouple cargo-near from rustup ([#146](https://github.com/near/cargo-near/pull/146))
</blockquote>
</p></details>
---
> chore: release v0.6.2

- cargo-near/src/commands/abi_command/abi.rs
- cargo-near/src/commands/abi_command/mod.rs
- cargo-near/src/commands/build_command/build.rs
- cargo-near/src/commands/build_command/docker.rs
- cargo-near/src/commands/build_command/mod.rs
- cargo-near/src/commands/mod.rs
- cargo-near/src/types/metadata.rs
- integration-tests/src/lib.rs
tested on https://github.com/dj8yfo/sample_no_workspace/tree/set_metadata and https://github.com/dj8yfo/sample_no_workspace/tree/set_metadata_locked_remove_lock
> feat(source-scan): implicit `--locked` by default, add `--no-locked` flag

- cargo-near/src/commands/abi_command/abi.rs
- cargo-near/src/commands/build_command/build.rs
- cargo-near/src/commands/build_command/docker/cloned_repo.rs
- cargo-near/src/types/metadata.rs
this addresses https://github.com/near/cargo-near/pull/153#discussion_r1575955226
screenshot from https://github.com/dj8yfo/sample_no_workspace/tree/metadata_image_repo_build_cmd
> feat(source-scan): precise docker build wasm input/destination

- cargo-near/src/commands/build_command/build.rs
- cargo-near/src/commands/build_command/mod.rs
- cargo-near/src/commands/deploy/mod.rs
- integration-tests/src/lib.rs
Adds support for passing feature flags to `cargo`.
Smart contract developers will sometimes use [feature flags](https://doc.rust-lang.org/cargo/reference/features.html#the-features-section) to enable/disable certain portions of code during compilation (e.g. enable certain debugging features for the testnet version which are not available in the production version).
```txt
cargo near build --features feat1,feat2
```
```txt
cargo near build --no-default-features
```
It does no validation of the input received to the flag, transparently forwarding it as an opaque string directly to `cargo`, after appending `near-sdk/__abi-embed` if necessary.
> Support passing feature flags to `cargo` invocation

- Cargo.lock
- README.md
- cargo-near/Cargo.toml
- cargo-near/src/build_extended.rs
- cargo-near/src/build_extended/build_script.rs
- cargo-near/src/commands/abi_command/abi.rs
- cargo-near/src/commands/build_command/build.rs
- cargo-near/src/commands/build_command/docker.rs
- cargo-near/src/commands/build_command/docker/cloned_repo.rs
- cargo-near/src/commands/build_command/docker/crate_in_repo.rs
- cargo-near/src/commands/build_command/docker/docker_checks.rs
- cargo-near/src/commands/build_command/docker/docker_checks/hello_world.rs
- cargo-near/src/commands/build_command/docker/docker_checks/pull_image.rs
- cargo-near/src/commands/build_command/docker/git_checks/pushed_to_remote.rs
- cargo-near/src/commands/build_command/docker/metadata.rs
- cargo-near/src/commands/build_command/mod.rs
- cargo-near/src/commands/new/new-project-template/README.md
- cargo-near/src/lib.rs
- cargo-near/src/main.rs
- cargo-near/src/util/mod.rs
- cargo-near/src/util/print.rs
fast-forward extension of #164 
1. [Cargo.toml](https://github.com/dj8yfo/sample_no_workspace/blob/1fd39bcbe4d523ac26c3d07c1f49ecc0fc65d9e7/Cargo.toml) => `sample-crate-12.testnet`
<details>
<summary>contract_source_metadata</summary><p>
```json
{
"build_info": {
"build_command": [
"cargo",
"near",
"build",
"--no-default-features",
"--features",
"near-sdk/expensive-debug"
],
"build_environment": "dj8yfo/sourcescan:0.x.x-dev-cargo-near-finalization@sha256:f86a095cb3daed21d0b5f86a4b5d9da0c0e26835f85c42678e1d460c9caa2c12",
"contract_path": "",
"source_code_snapshot": "git+https://github.com/dj8yfo/sample_no_workspace.git?rev=1fd39bcbe4d523ac26c3d07c1f49ecc0fc65d9e7"
},
"link": "https://github.com/dj8yfo/sample_no_workspace/tree/1fd39bcbe4d523ac26c3d07c1f49ecc0fc65d9e7",
"standards": [
{ …
```
> feat(source-scan): docker checks

- cargo-near/src/commands/new/new-project-template/.github/workflows/deploy-production.yml
- cargo-near/src/commands/new/new-project-template/.github/workflows/deploy-staging.yml
- cargo-near/src/commands/new/new-project-template/.github/workflows/undeploy-staging.yml
`cargo near new` creates a new contract from template with pre-populated git workflows.
It seems the versions of near-cli-rs and cargo-near are no longer compatible, getting error:
```
Error: 
0: expected `schema_version` to be ~0.3, but got 0.4.0: consider upgrading near-abi to a newer version
```
This pull request updates these two packages to latest versions. I've validated a successful deploy after modified workflows here: https://github.com/NEARBuilders/gateway/pull/457#issuecomment-2204429774
> Updates near-cli-rs and cargo-near to latest versions

- CHANGELOG.md
- Cargo.lock
- cargo-near/Cargo.toml
* `cargo-near`: 0.6.2 -> 0.6.3
<blockquote>
- Support passing feature flags to `cargo` invocation ([#160](https://github.com/near/cargo-near/pull/160))
- Also pass feature flags to ABI build step ([#161](https://github.com/near/cargo-near/pull/161))
- Updates near-cli-rs and cargo-near in the new project template to latest versions ([#168](https://github.com/near/cargo-near/pull/168))
- Updated dependencies to the latest versions ([#167](https://github.com/near/cargo-near/pull/167))
- Updated "interactive_clap" to 0.2.10 (updated "flatten" parameter) ([#154](https://github.com/near/cargo-near/pull/154))
</blockquote>
</p></details>
---
> chore: release v0.6.3

- CHANGELOG.md
- Cargo.lock
- cargo-near/Cargo.toml
- cargo-near/src/commands/new/new-project-template/.github/workflows/deploy-production.yml
- cargo-near/src/commands/new/new-project-template/.github/workflows/deploy-staging.yml
- cargo-near/src/commands/new/new-project-template/.github/workflows/undeploy-staging.yml
- integration-tests/src/lib.rs
- **chore: Updates near-cli-rs and cargo-near in the new project template to latest versions (#168)**
- **chore: release v0.6.3 (#155)**
- **test: Updated integration tests to use latest near-sdk-rs 5.2.1 (#171)**
> git: (WARN: requires create merge commit strategy) merge updates from `main`

- Cargo.lock
this resolves `cargo audit` lint (by `cargo update`)
```bash
Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
Loaded 642 security advisories (from /home/jerrick/.cargo/advisory-db)
Updating crates.io index
Scanning Cargo.lock for vulnerabilities (615 crate dependencies)
Crate:     openssl
Version:   0.10.64
Title:     `MemBio::get_buf` has undefined behavior with empty buffers
Date:      2024-07-21
ID:        RUSTSEC-2024-0357
URL:       https://rustsec.org/advisories/RUSTSEC-2024-0357
Solution:  Upgrade to >=0.10.66
Dependency tree:
openssl 0.10.64
├── near-cli-rs 0.11.1
│   ├── cargo-near 0.6.3
│   │   └── near-workspaces 0.11.0
│   │       └── cargo-near-integration-tests 0.1.0
│   └── cargo-near 0.6.3
│       └── cargo-near-integration-tests 0.1.0
├── …
```
> chore: update `Cargo.lock` with `cargo-audit` resolutions in patch-versions

- cargo-near/src/build_extended/build_script.rs
- cargo-near/src/commands/build_command/build.rs
- cargo-near/src/commands/build_command/docker/cloned_repo.rs
- cargo-near/src/commands/build_command/mod.rs
- cargo-near/src/util/mod.rs
addresses [bug](https://github.com/near/cargo-near/pull/179#issuecomment-2226846711)
Host with CLI built from [cargo-near branch](https://github.com/dj8yfo/cargo-near/tree/artificially_bumped_version):
From [docker](https://github.com/dj8yfo/cargo-near-image/blob/0.13.0-fake-dev-cargo-near-git/Dockerfile#L36) from [cargo-near branch](https://github.com/dj8yfo/cargo-near/tree/artificially_bumped_version):
--- 
```bash
near contract call-function as-read-only donation-product.repro-fct-37.testnet contract_source_metadata json-args {} network-config testnet now
```
=> 
<details>
<summary>donation-product.repro-fct-37.testnet</summary><p>
```json
{
"build_info": {
"build_command": [
"cargo",
"near",
"build"
],
"build_environment": "dj8yfo/sourcescan:0.x.x-dev-git-artif-0.13.0@sha256:bf0945f898 …
```
> feat(source-scan): coerce `cargo-near` version in nested builds (for abi)

- CHANGELOG.md
- Cargo.lock
- cargo-near/Cargo.toml
* `cargo-near`: 0.6.3 -> 0.6.4
<blockquote>
- Updated near-sdk and near-workspaces versions in the new project Cargo.toml.template ([#183](https://github.com/near/cargo-near/pull/183))
</blockquote>
</p></details>
---
> chore: release v0.6.4

- Cargo.lock
- cargo-near/src/commands/build_command/docker/docker_checks.rs
unfortunately, `cargo 1.80.0` has a bug, it successfully installs 0.6.4 version with `--locked` build, 
which has incorrect [dependencies](https://github.com/near/cargo-near/blob/source-scan-integration/Cargo.lock#L795-L827) specified
---
> chore: add linux in wsl docker site link; correct Cargo.lock

- CHANGELOG.md
- Cargo.lock
- cargo-near/Cargo.toml
* `cargo-near`: 0.6.4 -> 0.7.0
<blockquote>
- Added ability to use SourceScan ([#134](https://github.com/near/cargo-near/pull/134))
- Replacing atty unmaintained dependency ([#194](https://github.com/near/cargo-near/pull/194))
- update default docker images tags + digests ([#191](https://github.com/near/cargo-near/pull/191))
</blockquote>
</p></details>
---
> chore: release v0.7.0

- cargo-near/src/main.rs
alternative to #195 
this pr removes this section for non-debug (dev profile) builds:
it's enabled when binary is installed with `cargo install --locked --profile dev cargo-near`, 
when backtraces have source code info
> chore: disable env section of `color_eyre` report

- CHANGELOG.md
- Cargo.lock
- cargo-near/Cargo.toml
* `cargo-near`: 0.7.0 -> 0.8.0
<blockquote>
- [**breaking**] Updated near-* to 0.24, interactive clap to 0.3 ([#201](https://github.com/near/cargo-near/pull/201))
- disable env section of `color_eyre` report ([#196](https://github.com/near/cargo-near/pull/196))
</blockquote>
</p></details>
---
> chore: release v0.8.0

- CHANGELOG.md
- Cargo.lock
- cargo-near/Cargo.toml
* `cargo-near`: 0.8.0 -> 0.8.1
<blockquote>
- update Cargo.lock dependencies
</blockquote>
</p></details>
---
> chore: release v0.8.1

- CHANGELOG.md
- Cargo.lock
- cargo-near/Cargo.toml
* `cargo-near`: 0.8.1 -> 0.8.2
<blockquote>
- updated near-workspaces-rs ([#205](https://github.com/near/cargo-near/pull/205))
</blockquote>
</p></details>
---
> chore: release v0.8.2

- Cargo.lock
- cargo-near/Cargo.toml
- integration-tests/docker-build-template/Cargo.lock
- integration-tests/docker-build-template/Cargo.toml
near-workspaces in tests will be updated a bit later. As it's a circular dependency.
@race-of-sloths
> chore!: updates near-* packages to 0.25 version. Updates near-sdk to 5.4

- cargo-near-build/Cargo.toml
- release-plz.toml
attempt 2
https://github.com/near/cargo-near/actions/runs/10670519858/job/29574678361
https://github.com/near/cargo-near/actions/runs/10845014216
> ci: disable github release for `cargo-near-build` via cargo-dist

- CHANGELOG.md
- Cargo.lock
- cargo-near-build/CHANGELOG.md
- cargo-near-build/Cargo.toml
- cargo-near/Cargo.toml
- integration-tests/Cargo.toml
* `cargo-near`: 0.9.0 -> 0.10.0 (⚠️ API breaking changes)
* `cargo-near-build`: 0.1.1 -> 0.2.0 (⚠️ API breaking changes)
```
--- failure constructible_struct_adds_field: externally-constructible struct adds field ---
Description:
A pub struct constructible with a struct literal has a new pub field. Existing struct literals must be updated to include the new field.
ref: https://doc.rust-lang.org/reference/expressions/struct-expr.html
impl: https://github.com/obi1kenobi/cargo-semver-checks/tree/v0.35.0/src/lints/constructible_struct_adds_field.ron
Failed in:
field InteractiveClapContextScopeForBuildCommand.no_wasmopt in /tmp/.tmp9RlqrE/cargo-near/cargo-near/src/commands/build_command/mod.rs:5
field InteractiveClapContextScopeForBuildCommand.env in …
```
> chore: release

- cargo-near/src/commands/new/mod.rs
while a fuller solution might be done in scope of #238 
this pr is a quicker clarification of error
> chore: print `git` dep missing msg on `cargo near new`

- Cargo.lock
- cargo-near-build/src/lib.rs
fixes failures in https://github.com/near/cargo-near/actions/runs/12077533330
- **ci: fix audit lint by upgrading `rustls` (+ `url` warning)**
- **clippy: silence `needless_lifetimes` lint**
> ci: fix 1.83clippy, audit

- cargo-near/src/commands/new/new-project-template/.github/workflows/deploy-production.yml
- cargo-near/src/commands/new/new-project-template/.github/workflows/deploy-staging.yml
- cargo-near/src/commands/new/new-project-template/README.md
checked on https://github.com/dj8yfo/workflows_test/actions/runs/12243985822/job/34154726255 and https://github.com/dj8yfo/workflows_test/actions/runs/12244281047/job/34155683767 (mirroring change in https://github.com/dj8yfo/workflows_test/commit/5464b2c69c0cc5dfd51aeffeb80d8a88fa9b6be8)
> chore: change `.github/workflows` of `cargo near new` project (interactive build choice)

- cargo-near-build/src/fs.rs
- cargo-near-build/src/near/abi/mod.rs
- cargo-near-build/src/near/build/mod.rs
- cargo-near-build/src/pretty_print.rs
reason for this pr is that [LazyLock initialization block](https://github.com/NEAR-DevHub/neardevhub-contract/blob/083fdde69d147f43bd320094db1b3a8acf64c841/tests/test_env/mod.rs#L20-L27)
doesn't work to ensure tested contracts are built only once for `cargo nextest run` as **cargo-nextest** uses a process-per-test runner,
and for usual `cargo test` workflows it may not be convenient/possible to unite all tests into a single test module, thus contracts' build will run at least once per each test module. 
This pr minimizes time spent on contracts' rebuilding after initial build, so that LazyLock init block isn't that much needed any more, but it depends on separating target folders of different contracts being tested similar to https://github.com/dj8yfo/neardevhub-contract/commit/cbbf0ee589f …
> chore: optimize out retriggering 2nd stage of build + wasmopt stage

- README.md
- cargo-near-build/src/cargo_native/compile.rs
- cargo-near-build/src/env_keys.rs
- cargo-near-build/src/near/build/mod.rs
- cargo-near-build/src/types/near/docker_build/metadata.rs
resolves  #287 
this stuff gets set for build-scripts https://github.com/rust-lang/cargo/blob/master/src/cargo/core/compiler/custom_build.rs#L378, while `RUSTFLAGS` is unset
---
tested to help resolve problem in #287 on https://github.com/dj8yfo/neardevhub-treasury-dashboard/commit/56bcbcfe3a11e77af16f0b6e6fa4356955b42cd8
> fix: remove from env CARGO_ENCODED_RUSTFLAGS for easier nested builds, simplify RUSTFLAGS computation rule

- CHANGELOG.md
- Cargo.lock
- cargo-near-build/CHANGELOG.md
- cargo-near-build/Cargo.toml
- cargo-near/Cargo.toml
- integration-tests/Cargo.toml
* `cargo-near`: 0.13.3 -> 0.13.4 (✓ API compatible changes)
* `cargo-near-build`: 0.4.3 -> 0.4.4 (✓ API compatible changes)
<blockquote>
- embed docs for flags/arguments for `-h`/`--help` (#304)
- update `cargo near new` template `image` and `image_digest` ([#300](https://github.com/near/cargo-near/pull/300))
- update `cargo near new` template `image` and `image_digest` ([#298](https://github.com/near/cargo-near/pull/298))
</blockquote>
<blockquote>
- embed docs for flags/arguments for `-h`/`--help` (#304)
</blockquote>
</p></details>
---
This PR was generated with [release-plz](https://github.com/release-plz/release-plz/).
> chore: release 0.13.4 cargo-near; 0.4.4 cargo-near-build

- Cargo.lock
should fix audit workflow error https://github.com/near/cargo-near/actions/runs/13936911064/job/39006485508 , 
encountered in #315
> audit: update `ring` dep

- .github/workflows/release.yml
- Cargo.toml
Linux arm64 hosting runners are now available for free in public GitHub repositories
> feat: Use free ARM64 GitHub Action runners for pre-built binaries

- .github/workflows/cargo-near-v-release.yml
- .github/workflows/release.yml
- Cargo.toml
this is to avoid getting failed jobs of `cargo-dist` https://github.com/near/cargo-near/actions/runs/14329921815, 
triggered by tag for `cargo-near-build` created by `releaze-plz` job
https://github.com/near/cargo-near/actions/runs/14329795161/job/40162981199
And removing tag creation completely for `cargo-near-build` isn't cool too, it's kind of nice to pinpoint `cargo-near-build` release version
> ci: make on.push.tags value more precise for ./.github/workflows/release.yml job

- .github/workflows/cargo-near-v-release.yml
- Cargo.toml
https://github.com/near/cargo-near/actions/runs/14337495343
> ci: replace ubuntu-20.04, being browned out

- CHANGELOG.md
- Cargo.lock
- cargo-near-build/CHANGELOG.md
- cargo-near-build/Cargo.toml
- cargo-near/Cargo.toml
- integration-tests/Cargo.toml
* `cargo-near-build`: 0.4.6 -> 0.5.0 (⚠ API breaking changes)
* `cargo-near`: 0.13.6 -> 0.14.0 (✓ API compatible changes)
```text
--- failure feature_missing: package feature removed or renamed ---
Description:
A feature has been removed from this package's Cargo.toml. This will break downstream crates which enable that feature.
ref: https://doc.rust-lang.org/cargo/reference/semver.html#cargo-feature-remove
impl: https://github.com/obi1kenobi/cargo-semver-checks/tree/v0.40.0/src/lints/feature_missing.ron
Failed in:
feature build_script in the package's Cargo.toml
--- failure function_missing: pub fn removed or renamed ---
Description:
A publicly-visible function cannot be imported by its prior path. A `pub use` may have been removed, or the function itself may have been renamed or removed …
```
> chore: release cargo-near 0.14.0, cargo-near-build 0.5.0

- cargo-near-build/Cargo.toml
- cargo-near-build/src/near/docker_build/warn_versions_upgrades.rs
fixes https://docs.rs/crate/cargo-near-build/0.5.0/builds/2021086 
(`build_script` feature was removed in scope of #328 )
> fix: doc publish. Change reference to `latest` instead of specific version

- CHANGELOG.md
- Cargo.lock
- cargo-near-build/CHANGELOG.md
- cargo-near-build/Cargo.toml
- cargo-near/Cargo.toml
- integration-tests/Cargo.toml
* `cargo-near-build`: 0.5.0 -> 0.5.1 (✓ API compatible changes)
* `cargo-near`: 0.14.0 -> 0.14.1 (✓ API compatible changes)
<blockquote>
- doc publish. Change reference to `latest` instead of specific version ([#329](https://github.com/near/cargo-near/pull/329))
</blockquote>
<blockquote>
- doc publish. Change reference to `latest` instead of specific version ([#329](https://github.com/near/cargo-near/pull/329))
</blockquote>
</p></details>
---
This PR was generated with [release-plz](https://github.com/release-plz/release-plz/).
> chore: release cargo-near 0.14.1, cargo-near-build 0.5.1

- .github/workflows/test.yml
- Cargo.lock
- README.md
- cargo-near/src/commands/new/new-project-template/.github/workflows/test.yml
- cargo-near/src/commands/new/new-project-template/Cargo.template.toml
- integration-tests/Cargo.toml
- integration-tests/src/lib.rs
- integration-tests/tests/cargo_near_new.rs
after updating `near-workspaces` to 0.19 the ci of this project starts to depend on installing `cargo-near` for test job 
https://github.com/near/cargo-near/actions/runs/14865274164/job/41740403384, 
as `cargo-near-integration-tests::cargo_near_new::test_cargo_test_on_generated_project` tests an end-to-end scenario from an external user's point of view, who runs
```
cargo near new skeleton
cd skeleton
cargo test
```
---
this pr is better be merged before #338 to be able to release it separately (template update)
> ci: `cargo-near-build` crate badge + install cli in integration tests (for `test_cargo_test_on_generated_project`)

- CHANGELOG.md
- Cargo.lock
- cargo-near-build/CHANGELOG.md
- cargo-near-build/Cargo.toml
- cargo-near/Cargo.toml
- integration-tests/Cargo.toml
* `cargo-near-build`: 0.6.0 -> 0.7.0 (⚠ API breaking changes)
* `cargo-near`: 0.14.2 -> 0.15.0 (⚠ API breaking changes)
```text
--- failure constructible_struct_adds_field: externally-constructible struct adds field ---
Description:
A pub struct constructible with a struct literal has a new pub field. Existing struct literals must be updated to include the new field.
ref: https://doc.rust-lang.org/reference/expressions/struct-expr.html
impl: https://github.com/obi1kenobi/cargo-semver-checks/tree/v0.41.0/src/lints/constructible_struct_adds_field.ron
Failed in:
field Opts.override_toolchain in /tmp/.tmpy3xYMR/cargo-near/cargo-near-build/src/types/near/build/input/mod.rs:79
--- failure method_parameter_count_changed: pub method parameter count changed ---
Description:
A publicly-visible …
```
> chore: release `cargo-near 0.15.0`, `cargo-near-build 0.7.0`

- cargo-near/src/commands/new/new-project-template/.github/workflows/deploy-production.yml
- cargo-near/src/commands/new/new-project-template/.github/workflows/deploy-staging.yml
- cargo-near/src/commands/new/new-project-template/.github/workflows/undeploy-staging.yml
- cargo-near/src/commands/new/new-project-template/rust-toolchain.toml
- docs/workflows.md
This fixes template after a small breaking change in `near-cli-rs`, which has slipped in unnoticed. 
tested in 
- ok, deploy production in https://github.com/near/cargo-near-new-project-template/actions/runs/15110669333 after update in https://github.com/near/cargo-near-new-project-template/commit/c1b1d6dde10865e12bdb704dfae60cc0426b8a16
- fails, staging deploy from [pr](https://github.com/near/cargo-near-new-project-template/pull/20) from fork https://github.com/near/cargo-near-new-project-template/actions/runs/15112189405 (this fails as pr has no access to repository variables)
- ok, staging deploy from [pr](https://github.com/near/cargo-near-new-project-template/pull/21)  the same repo https://github.com/near/cargo-near-new-project-template/actions/runs/15112293518
- ok, staging …
> chore: update `near-cli` install in template workflows to 0.20.0; update `sign-with-plaintext-private-key` cli flag -> argument usage
